# Dockerfile_BE
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["BE.csproj", "./"]
RUN dotnet restore "BE.csproj"
COPY . .
RUN dotnet publish "BE.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app

# Mount HTTPS folder từ host vào container
VOLUME ["/https"]

# Tạo cert dev nếu chưa có
RUN if [ ! -f /https/aspnetapp.pfx ]; then \
        dotnet dev-certs https -ep /https/aspnetapp.pfx -p 123456; \
    fi

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "BE.dll"]
